
version: '3.5'

networks:
  spring-cloud-network:
  kafka-network:

services:

  poc-kafka:
    image: spotify/kafka:latest
    ports:
      - 2181:2181
      - 9092:9092
    networks:
      - kafka-network
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092

  poc-eureka:
    build:
      context: ./poc-eureka
    ports:
      - 8000:8080
    networks:
      - spring-cloud-network

  poc-agent:
    build:
      context: ./poc-agent
    networks:
      - spring-cloud-network
      - kafka-network

  poc-customer:
    build:
      context: ./poc-customer
    networks:
      - spring-cloud-network
      - kafka-network

  poc-order:
    build:
      context: ./poc-order
    networks:
      - spring-cloud-network
      - kafka-network

  poc-proposal:
    build:
      context: ./poc-proposal
    networks:
      - spring-cloud-network
      - kafka-network