spring:
  application:
    name: poc-proposal

server:
  port: 8080

management:
  security:
    enabled: false

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://poc-eureka:8080/eureka/
    registerWithEureka: true