spring:
  application:
    name: poc-agent

server:
  port: 8080

management:
  security:
    enabled: false

kafka:
  server:
    ip: poc-kafka
    port: 9092
  topic:
    name: poc-metrics

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://poc-eureka:8080/eureka/
    registerWithEureka: true