spring:
  application:
    name: poc-eureka

server:
  port: 8080

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: poc-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false